# Generated by Django 5.0 on 2024-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockxuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="stockxuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
