# Generated by Django 5.0 on 2024-03-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_quantity_product_initial_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="size_range",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sizerange",
            ),
            preserve_default=False,
        ),
    ]
