# Generated by Django 5.0 on 2024-04-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_stockxuser_email_stockxuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="location",
        ),
    ]
