# Generated by Django 5.0 on 2024-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_stocktransaction_size_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_available",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
