# Generated by Django 5.0 on 2024-04-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_product_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockxuser",
            name="tg_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
