# Generated by Django 5.0 on 2024-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_quantity_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_type",
            field=models.CharField(
                choices=[("1", "stock in"), ("2", "stock out")], default=1, max_length=2
            ),
            preserve_default=False,
        ),
    ]
