# Generated by Django 5.0 on 2024-03-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_stocktransaction_stock_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocktransaction",
            old_name="added_by",
            new_name="modified_by",
        ),
    ]
