# Generated by Django 5.0 on 2024-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_stockxuser_created_at_storeuser_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockxuser",
            name="upated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
