# Generated by Django 5.0 on 2024-04-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_stockxuser_upated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockxuser",
            old_name="upated_at",
            new_name="updated_at",
        ),
    ]
