# Generated by Django 5.0 on 2024-03-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_added_by_stocktransaction_modified_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocktransaction",
            old_name="quantity_added",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="salestransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="stock_type",
            field=models.CharField(
                blank=True,
                choices=[("1", "stock in"), ("2", "stock out")],
                default=1,
                max_length=2,
            ),
        ),
    ]
