# Generated by Django 5.0 on 2024-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_quantity_added_stocktransaction_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
