# Generated by Django 5.0 on 2024-03-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_brand_created_at_brand_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salestransaction",
            old_name="soled_by",
            new_name="sold_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity_available",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="size_range",
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="core.product",
            ),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_on_hand", models.PositiveIntegerField(blank=True, default=0)),
                ("modified_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
