# Generated by Django 5.0 on 2024-03-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_soled_by_salestransaction_sold_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
