# Generated by Django 5.0 on 2024-03-31 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_product_low_stock_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salestransaction",
            name="sale_date",
        ),
        migrations.RemoveField(
            model_name="salestransaction",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.brand"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="salestransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_transactions",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="stock_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="stock_type",
            field=models.CharField(
                choices=[("IN", "Stock In"), ("OUT", "Stock Out")], max_length=3
            ),
        ),
    ]
