# Generated by Django 5.0 on 2024-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_salestransaction_sale_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salestransaction",
            name="selling_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="salestransaction",
            name="total_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
