# Generated by Django 5.0 on 2024-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_salestransaction_selling_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="stock_type",
            field=models.CharField(
                choices=[("1", "Stock In"), ("2", "Stock Out")], max_length=1
            ),
        ),
    ]
