# Generated by Django 5.0 on 2024-03-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_stocktransaction_stock_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salestransaction",
            old_name="selling_price",
            new_name="unit_price",
        ),
    ]
