# Generated by Django 5.0 on 2024-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_selling_price_salestransaction_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="created_by",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="stock_type",
            field=models.CharField(
                choices=[("1", "In 🟢"), ("2", "Out🔺")], max_length=1
            ),
        ),
    ]
