# Generated by Django 5.0 on 2024-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_stock_created_by_alter_stocktransaction_stock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_on_hand",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Quantity"
            ),
        ),
    ]
